In [21]:
# BÀI THỰC HÀNH 1
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
print(a)
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
print(b)
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]], dtype=object)
print(c)
A = np.random.random((2, 2))
print(A)
B = np.array(b)
print(B)
C = np.random.random((10, 5))
print(C)
D = np.array([[4, 3], [2, 6]])
print(D)
F = np.eye(3, k=1)
print(F)
print(np.linalg.matrix_rank(C))
print(np.linalg.inv(A))
print(linalg.det(A))
print(A.T)
print(A.conj().T)
b2 = np.array([1, 2])
x = linalg.solve(A, b2)
print(x)
E = a.reshape(-1, 1)
x_lstsq, res, rnk, s = linalg.lstsq(F, E)
print(x_lstsq)
print(np.add(A, D))
print(np.subtract(A, D))
print(np.divide(A, D))
print(A @ D)
print(np.multiply(D, A))
print(np.dot(A, D))
print(np.vdot(A, D))
print(linalg.expm(A))
print(linalg.logm(A))


[1 2 3]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[[0.5 1.5 10]
  [3 2 1]]

 [[6 5 4]
  [7 8 9]]]
[[0.07265165 0.73219705]
 [0.53966121 0.57034825]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.39550331 0.08703438 0.37580411 0.284112   0.8683165 ]
 [0.77305326 0.11251876 0.15826882 0.96777368 0.52603227]
 [0.75152649 0.06127426 0.52890683 0.1931134  0.43773254]
 [0.22726761 0.17826405 0.58758624 0.56168073 0.94744498]
 [0.43009948 0.70602038 0.07851271 0.32167242 0.99324419]
 [0.64455511 0.28490615 0.85740604 0.18728819 0.16555177]
 [0.44651483 0.02412052 0.74339263 0.83586042 0.9283295 ]
 [0.97548441 0.57946073 0.17243067 0.09942001 0.52176642]
 [0.54644251 0.7417408  0.78710537 0.97242574 0.64151061]
 [0.79620934 0.99466939 0.15151142 0.27192863 0.75719662]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
5
[[-1.61251249  2.0700982 ]
 [ 1.52575281 -0.2054038 ]]
-0.3537016000062874
[[0.07265165 0.53966121]
 [0.73219705 0.57034825]]
[[0.07265165 0.53966121]
 [0.7321

In [25]:
# BÀI THỰC HÀNH 2
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A)
temp = A.dot(A)
print(temp)
k= 6
for i in range(k-1):
    temp = temp.dot(A)
print (temp)
print('---')
B = np.array([ [0,-1], [-1,0]])
print(B)
temp = B.dot(B)
print(temp)
k= 5
for i in range(k-1):
    temp = temp.dot(B)
print (temp)
print('---')
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)
temp = C.dot(C) 
print(temp)
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp)
k = 1000
for i in range(k-1):
     temp = temp.dot(C)
print(temp) 
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M)
print(MM)
MM = M.dot(M) 
print (MM)
for i in range(100):
    MM = MM.dot(M)
print(MM)


[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
---
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.7  0.45]
 [0.3  0.55]]
[[0.7  0.45]
 [0.3  0.55]]
[[0.6 0.6]
 [0.4 0.4]]


In [1]:
# BÀI THỤC HÀNH 3
import numpy as np
from scipy import linalg
M = np.array([[0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M)
print("P =\n", P)
print("L =\n", L)
print("U =\n", U)
print("L @ U =\n", L @ U)
print("P @ L @ U =\n", P @ L @ U)  

P =
 [[1. 0.]
 [0. 1.]]
L =
 [[1.   0.  ]
 [0.25 1.  ]]
U =
 [[0.8   0.3  ]
 [0.    0.625]]
L @ U =
 [[0.8 0.3]
 [0.2 0.7]]
P @ L @ U =
 [[0.8 0.3]
 [0.2 0.7]]


In [2]:
# BÀI THỰC HÀNH 5
A = np.array([[0,1,0,1],[0,0,1,0], [1,0,0,1],[1,1,0,0]])
temp = A.dot(A) 
print(temp)
temp = temp.dot(A) 
print(temp)
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
    temp = temp.dot(A)
    sumA = sumA + temp
print (temp)
print (sumA)




[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


In [7]:
# BÀI TẬP 1
import numpy as np
A = np.array([[2, 1, 3],[0, 1, 4], [5, 2, 1]])
print("Ma trận A:")
print(A)
det = np.linalg.det(A)
if det != 0:
    print("Ma trận khả nghịch vì định thức khác 0:", det)
    A_inv = np.linalg.inv(A)
text = "Do Hoang Long"
def text_to_vector(text):
    ascii_vals = [ord(c) for c in text]
    while len(ascii_vals) % 3 != 0:
        ascii_vals.append(32) 
    return np.array(ascii_vals).reshape(-1, 3).T
def encrypt(text_vec, matrix):
    return np.dot(matrix, text_vec)
vec = text_to_vector(text)
encrypted = encrypt(vec, A)
print("Mã hóa:")
print(encrypted)
def decrypt(enc_vec, matrix_inv):
    return np.dot(matrix_inv, enc_vec)
decrypted = decrypt(encrypted, A_inv).round().astype(int)
decrypted_text = ''.join([chr(num) for num in decrypted.T.flatten()])
print("Giải mã:")
print(decrypted_text)


Ma trận A:
[[2 1 3]
 [0 1 4]
 [5 2 1]]
Ma trận khả nghịch vì định thức khác 0: -9.000000000000002
Mã hóa:
[[343 546 419 593 334]
 [239 499 231 551 160]
 [594 679 788 712 611]]
Giải mã:
Do Hoang Long  


In [8]:
# BÀI TẬP 2
from fractions import Fraction
def continued_fraction_to_fraction(coeffs):
    result = Fraction(coeffs[-1])
    for c in reversed(coeffs[:-1]):
        result = c + Fraction(1, result)
    return result.numerator, result.denominator
coeffs = [3, 1, 2]
pn, qn = continued_fraction_to_fraction(coeffs)
print("Kết quả pn/qn:", pn, "/", qn)
from sympy import Matrix
def verify_matrix_formula(coeffs):
    M = Matrix([[1, 0], [0, 1]])
    for c in coeffs:
        M = M * Matrix([[c, 1], [1, 0]])
    return M[0, 0], M[1, 0]
pn2, qn2 = verify_matrix_formula(coeffs)
print("Kiểm chứng bằng ma trận:", pn2, "/", qn2)


Kết quả pn/qn: 11 / 3
Kiểm chứng bằng ma trận: 11 / 3
