In [9]:
# BÀI THỰC HÀNH 2
import numpy as np 
scores = np.array([-1,1,2,-3,5,-4])
print(np.select([scores >= 0, scores < 0], ['so duong', 'so am'], default='khong xac dinh'))
scores = np.array([-1,1,2,0,-3,5,0,-4])
print(np.select([scores > 0, scores == 0, scores < 0], ['so duong', 'so 0', 'so am'], default='khong xac dinh'))

['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']
['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


In [18]:
# BAÌ THỰC HÀNH 5
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem)



{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [19]:
# BÀI TẬP 1
import numpy as np

A1 = np.array([[1, -1], [2, 3]])
b1 = np.array([-2, 6])
x1 = np.linalg.solve(A1, b1)
print("Problem 1 – Nghiệm:", x1)

A2 = np.array([[1, -1, 0], [2, -1, -1], [1, 1, 1]])
b2 = np.array([2, 3, 6])
x2 = np.linalg.solve(A2, b2)
print("Problem 2 – Nghiệm:", x2)

A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
b3 = np.array([4, 3, 4])
x3 = np.linalg.solve(A3, b3)
print("Problem 3 – Hệ số đa thức (a, b, c):", x3)

A4 = np.array([[1, 0, 1], [1, 1, -2], [-2, 2, 1]])
b4 = np.array([1, -3, 0])
x4 = np.linalg.solve(A4, b4)
print("Problem 4 – Hệ số phân rã (a, b, c):", x4)


Problem 1 – Nghiệm: [0. 2.]
Problem 2 – Nghiệm: [3. 1. 2.]
Problem 3 – Hệ số đa thức (a, b, c): [ 1. -4.  7.]
Problem 4 – Hệ số phân rã (a, b, c): [-0.11111111 -0.66666667  1.11111111]


In [20]:
# BÀI TẬP 2
from sympy import symbols, Eq, solve, Matrix
x, y = symbols('x y')
eq1 = Eq(x - y, -2)
eq2 = Eq(2*x + 3*y, 6)
sol1 = solve((eq1, eq2), (x, y))
print("Problem 1:", sol1)

x, y, z = symbols('x y z')
eq1 = Eq(x - y, 2)
eq2 = Eq(2*x - y - z, 3)
eq3 = Eq(x + y + z, 6)
sol2 = solve((eq1, eq2, eq3), (x, y, z))
print("Problem 2:", sol2)

a, b, c = symbols('a b c')
eq1 = Eq(a + b + c, 4)
eq2 = Eq(4*a + 2*b + c, 3)
eq3 = Eq(9*a + 3*b + c, 4)
sol3 = solve((eq1, eq2, eq3), (a, b, c))
print("Problem 3:", sol3)

eq1 = Eq(a + c, 1)
eq2 = Eq(a + b - 2*c, -3)
eq3 = Eq(-2*a + 2*b + c, 0)
sol4 = solve((eq1, eq2, eq3), (a, b, c))
print("Problem 4:", sol4)


Problem 1: {x: 0, y: 2}
Problem 2: {x: 3, y: 1, z: 2}
Problem 3: {a: 1, b: -4, c: 7}
Problem 4: {a: -1/9, b: -2/3, c: 10/9}


In [ ]:
# BÀI TẬP 3
import numpy as np
def fib_matrix(k):
    F = np.array([[1, 1], [1, 0]], dtype=object)
    return np.linalg.matrix_power(F, k)

def fibonacci(n):
    fib = [0, 1]
    for i in range(2, n+2):
        fib.append(fib[-1] + fib[-2])
    return fib

k = 7
Fk = fib_matrix(k)
fib_seq = fibonacci(k+1)
print("F^k:")
print(Fk)
print("So sánh với Fibonacci:")
print(f"Fib[{k+1}] = {fib_seq[k+1]}, Fib[{k}] = {fib_seq[k]}, Fib[{k-1}] = {fib_seq[k-1]}")


In [12]:
# BÀI THỰC HÀNH 4
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
print(b)

[89 55]


In [ ]:
# BÀI THỰCỰC HÀNH 1
def scale(a,v):
  return [a*vi for vi in v]
v = [3,5,7]
print(scale(10,v))
def sumvector(v,w):
  return[vi + wi for (vi,wi) in zip(v,w)]
v = [3,5,7]
w = [2,4,6]
print(sumvector(v,w))
def dotvector(v,w):
  return sum([vi*wi for (vi, wi) in zip(v, w)])
print(dotvector(v,w))
def lenvector(v):
  return dotvector(v,v)
print(lenvector(w))
  

[30, 50, 70]
[5, 9, 13]
68
56


In [ ]:
# BÀI THỰC HÀNH 3
import numpy as np
from scipy import linalg
np.random.seed(0)
D = np.asmatrix([[3, 4], [5, 6]])
print("D =")
print(D)
C = np.asmatrix(np.random.random((5, 7)))
print("\nC =")
print(C)
A = np.asmatrix(np.random.random((2, 2)))
print("\nA =")
print(A)
b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)
print("\nb (array) =")
print(b)
print("\nB (matrix) =")
print(B)
print("\nA.T =")
print(A.T)
print("\nA.I =")
print(A.I)
print("\ninv(A) =")
print(linalg.inv(A))
M = np.array([[-1, 3, 2], [ 0, -2, 1], [ 1,  5, -2]])
print("\nM_lower =")
print(np.tril(M))
print("\nM_upper =")
print(np.triu(M))
v_diag = np.diag(M)
print("\nv_diag =")
print(v_diag)
print("\nM_diag =")
print(np.diag(v_diag))


D =
[[3 4]
 [5 6]]

C =
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
  0.43758721]
 [0.891773   0.96366276 0.38344152 0.79172504 0.52889492 0.56804456
  0.92559664]
 [0.07103606 0.0871293  0.0202184  0.83261985 0.77815675 0.87001215
  0.97861834]
 [0.79915856 0.46147936 0.78052918 0.11827443 0.63992102 0.14335329
  0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369 0.45615033 0.56843395
  0.0187898 ]]

A =
[[0.6176355  0.61209572]
 [0.616934   0.94374808]]

b (array) =
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]

B (matrix) =
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]

A.T =
[[0.6176355  0.616934  ]
 [0.61209572 0.94374808]]

A.I =
[[ 4.59760157 -2.98191045]
 [-3.00548078  3.00889824]]

inv(A) =
[[ 4.59760157 -2.98191045]
 [-3.00548078  3.00889824]]

M_lower =
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]

M_upper =
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]

v_diag =
[-1 -2 -2]

M_diag =
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]
