In [ ]:
# BÀI THỰC HÀNH 1
import numpy as np 
n = 4
X = np.array(range(1,n+1))
sigma = np.array([4,3,2,1])
def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X)-1):
            for j in range(i+1,len(X)):
                 ket_qua = ket_qua * ((X[i]-X[j])/(sigma[i]-sigma[j]))
                 return int(ket_qua)
sigma = np.array([2,1,3,4])
print(sgn_by_def(sigma))
sigma = np.array([1,2,3,4])
print(sgn_by_def(sigma))
sigma = np.array([4,3,2,1])
print(sgn_by_def(sigma))

from itertools import permutations
n = 3
X = []
for i in range (1, n+1):
    X.append(i)
Sn = list(permutations(X)) 
print (Sn)
det = 0

import numpy as np
def phatsinh_dinhthuc(n):
     X = []
     for i in range(1,n+1):
          X.append(i)
Sn = list(permutations(X))
dinhthuc = ""
for sn in Sn:
     sigma = np.array([1])
     sigma.resize



[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [ ]:
# ĐỊNH THỨC
from itertools import permutations
import numpy as np
import math
def sgn_by_def(permutation):
    inversions = 0
    n = len(permutation)
    for i in range(n):
        for j in range(i + 1, n):
            if permutation[i] > permutation[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1

n = 3
X = []
for i in range(1, n+1):
    X.append(i)
Sn = list(permutations(X)) 
print(Sn)

def phatsinh_dinhthuc(n):
    X = list(range(1, n + 1)) 
    Sn = list(permutations(X))  
    dinhthuc = ""
    for sn in Sn:
        product = ""
        for i in range(1, n + 1):
            product += "a" + str(i) + str(sn[i - 1])
        dau = sgn_by_def(list(sn))
        if dau == 1:
            dinhthuc += "+" + product
        else:
            dinhthuc += "-" + product
    return dinhthuc
print(phatsinh_dinhthuc(3))

def tinhtoan_dinhthuc(A):
    X = []
    n = int(math.sqrt(A.size))
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product *= A[i-1][sn.index(i)] 
        dau = sgn_by_def(sigma)  
        if (dau == 1):
            dinhthuc = dinhthuc + product
        else:
            dinhthuc = dinhthuc + product * (-1)  
    return dinhthuc

matran = np.array([[3, 5, -8], [4, 12, -1], [2, 5, 3]])
print(tinhtoan_dinhthuc(matran))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
+a11a22a33-a11a23a32-a12a21a33+a12a23a31+a13a21a32-a13a22a31
85


In [8]:
# BÀI THỰC HÀNH 2
import numpy as np

def get_minor_matrix(A, i, j):
    return np.delete(np.delete(A, i, axis=0), j, axis=1)

def determinant(A):
    if A.shape == (2, 2):
        return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]
    det = 0
    for j in range(A.shape[1]):
        det += ((-1) ** j) * A[0, j] * determinant(get_minor_matrix(A, 0, j))
    return det

def cofactor_matrix(A):
    n = A.shape[0]
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            C[i, j] = ((-1) ** (i + j)) * determinant(get_minor_matrix(A, i, j))
    return C

def adjoint_matrix(A):
    return cofactor_matrix(A).T

def inverse_matrix(A):
    det_A = determinant(A)
    if det_A == 0:
        raise ValueError("Ma trận không khả nghịch (determinant = 0)")
    return (1 / det_A) * adjoint_matrix(A)

A = np.array([[3, 5, -8],
              [4, 12, -1],
              [2, 5, 3]])

A_inv = inverse_matrix(A)
print("Ma trận A:")
print(A)
print("Ma trận nghịch đảo A^-1:")
print(A_inv)
print("Kiểm tra AA^-1:")
print(np.dot(A, A_inv))

Ma trận A:
[[ 3  5 -8]
 [ 4 12 -1]
 [ 2  5  3]]
Ma trận nghịch đảo A^-1:
[[ 0.48235294 -0.64705882  1.07058824]
 [-0.16470588  0.29411765 -0.34117647]
 [-0.04705882 -0.05882353  0.18823529]]
Kiểm tra AA^-1:
[[ 1.00000000e+00 -1.66533454e-16  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00 -2.22044605e-16]
 [ 2.77555756e-17 -1.38777878e-17  1.00000000e+00]]


In [10]:
# BÀI THỰC HÀNH 3
import numpy as np
from scipy import linalg

A = np.array([[1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])
b = np.array([1, 3, 2])

detA = linalg.det(A)

A1 = np.array([[b[0], 2, -3],
               [b[1], -2, 1],
               [b[2], -4, 4]])
A2 = np.array([[1, b[0], -3],
               [2, b[1], 1],
               [3, b[2], 4]])
A3 = np.array([[1, 2, b[0]],
               [2, -2, b[1]],
               [3, -4, b[2]]])

detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
detA3 = linalg.det(A3)

if detA != 0:
    x = detA1 / detA
    y = detA2 / detA
    z = detA3 / detA
    print("Nghiệm của phương trình:", "x =", x, "y =", y, "z =", z)


Nghiệm của phương trình: x = -0.0 y = -2.499999999999999 z = -1.9999999999999991


In [11]:
# BÀI THỰC HÀNH 5
from sympy import *
x, y = symbols('x y')
MP = Matrix([[x*y, y**2, x, y, 1],
             [1*0, 0**2, 1, 0, 1],
             [2*1, 1**2, 2, 1, 1],
             [3*2, 2**2, 3, 2, 1],
             [4*3, 3**2, 4, 3, 1]])
equation = MP.det()
print("Phương trình đường cong ellipse:", equation)

Phương trình đường cong ellipse: 0


In [12]:
# BÀI THỰC HÀNH 4
from sympy import *
x, y, z = symbols('x y z')
MP = Matrix([[x, y, z, 1], [-1, 3, 2, 1], [0, 1, 0, 1], [-2, 0, 1, 1]])
equation = MP.det()
print("Phương trình mặt phẳng:", equation)

Phương trình mặt phẳng: -4*x + 3*y - 5*z - 3


In [13]:
# BÀI TẬP 1
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
def cofactor_matrix(matrix):
    n = matrix.shape[0]
    cofactors = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            cofactors[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    return cofactors
cofactor = cofactor_matrix(A)
print("Ma trận hệ số kép (cofactor matrix):")
print(cofactor)
adjoint = cofactor.T
print("Ma trận liên hợp (adjoint matrix):")
print(adjoint)

Ma trận hệ số kép (cofactor matrix):
[[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]
Ma trận liên hợp (adjoint matrix):
[[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]


In [ ]:
# BÀI TẬP 2
from sympy import *

x, y = symbols('x y')
MP = Matrix([[x**2 + y**2, x, y, 1],
             [1**2 + 0**2, 1, 0, 1],
             [2**2 + 1**2, 2, 1, 1],
             [3**2 + 2**2, 3, 2, 1]])
equation = MP.det()
print("Phương trình đường cong (ellipse):")
print(equation)