In [ ]:
# BÀI THỰC HÀNH 1
import numpy as np
from numpy import matlib
print("=== 1.1. Các cách sao chép mảng ===")
A = np.array([[1, 2], [3, 4]])
B1 = A
print("B1 (tham chiếu A):\n", B1)
B2 = np.copy(A)
print("B2 (np.copy):\n", B2)
B3 = A.copy()
print("B3 (A.copy()):\n", B3)

E = np.array([[1, 2], [3, 5]])
np.copyto(E, A)
print("E sau khi copyto từ A:\n", E)

print("\n=== 1.2. Nên / không nên dùng numpy.matrix ===")
B = np.matrix("[1 2 3; 4 5 6]")
print("Ma trận B:\n", B)
print("B.T (transpose):\n", B.T)
print("B.H (conjugate transpose):\n", B.H)
print("B.I (nghịch đảo, nếu khả thi):")
try:
    print(np.matrix("[1 2; 3 4]").I)
except np.linalg.LinAlgError as e:
    print("Lỗi:", e)
print("\n=== Mảng chứa object (dùng array) ===")
x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
C = np.array([[x, y], [1, 2]], dtype=object)
print("Mảng C chứa object:\n", C)
print("\n=== Kiểm tra lỗi khi tạo matrix 3 chiều ===")
try:
    A3 = np.matrix([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
except ValueError as e:
    print("Lỗi:", e)
A_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Array 3 chiều:\n", A_array)

print("\n=== 1.3. Dùng numpy.matlib để tạo matrix ===")
G = matlib.identity(5)
print("Ma trận đơn vị G:\n", G)

H = matlib.randn(3, 2)
print("Ma trận ngẫu nhiên H:\n", H)

K = matlib.zeros([4, 4])
print("Ma trận K toàn 0:\n", K)

=== 1.1. Các cách sao chép mảng ===
B1 (tham chiếu A):
 [[1 2]
 [3 4]]
B2 (np.copy):
 [[1 2]
 [3 4]]
B3 (A.copy()):
 [[1 2]
 [3 4]]
E sau khi copyto từ A:
 [[1 2]
 [3 4]]

=== 1.2. Nên / không nên dùng numpy.matrix ===
Ma trận B:
 [[1 2 3]
 [4 5 6]]
B.T (transpose):
 [[1 4]
 [2 5]
 [3 6]]
B.H (conjugate transpose):
 [[1 4]
 [2 5]
 [3 6]]
B.I (nghịch đảo, nếu khả thi):
[[-2.   1. ]
 [ 1.5 -0.5]]

=== Mảng chứa object (dùng array) ===
Mảng C chứa object:
 [[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]

=== Kiểm tra lỗi khi tạo matrix 3 chiều ===
Lỗi: matrix must be 2-dimensional
Array 3 chiều:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

=== 1.3. Dùng numpy.matlib để tạo matrix ===
Ma trận đơn vị G:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Ma trận ngẫu nhiên H:
 [[-0.27684836  1.48395921]
 [-0.00234846 -1.01306041]
 [-0.06890632 -0.08824434]]
Ma trận K toàn 0:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# BÀI THỰC HÀNH 2
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
for i in range(len(c)):
    ci = np.asmatrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M @ ci 

print("Ma trận kết quả:\n", M)
print("Số Pi xấp xỉ theo liên phân số:", M[0, 0] / M[1, 0])

Ma trận kết quả:
 [[165707065  80143857]
 [ 52746197  25510582]]
Số Pi xấp xỉ theo liên phân số: 3.1415926535897936


In [9]:
# BÀI THỰC HÀNH 3
import numpy as np
X = np.array([[1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])

Y = np.array([[2],
              [4],
              [6],
              [8],
              [10]])
XT = X.T
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)
A = A1.dot(A2)

print("Hệ số A (a0, a1):")
print(A)
a0 = A[0, 0]
a1 = A[1, 0]
print(f"Phương trình: f(x) = {a0:.2f} + {a1:.2f} * x")
Y_pred = X.dot(A)
error = np.sum((Y_pred - Y)**2)
print("Tổng bình phương sai số:", error)


Hệ số A (a0, a1):
[[1.77635684e-15]
 [2.00000000e+00]]
Phương trình: f(x) = 0.00 + 2.00 * x
Tổng bình phương sai số: 4.9895452255228997e-29


In [10]:
# BÀI TẬP 1
import numpy as np

def bpcuctieu(y_values):
    n = len(y_values)
    x0 = [1.0] * n           
    x1 = [float(i) for i in range(n)]  
    x = np.array([x0, x1])
    u = np.dot(x, x.T)
    u_inv = np.linalg.inv(u)
    v = np.dot(u_inv, x)
    y = np.array(y_values)
    A = np.dot(v, y)
    return A 
dulieu = [10.0, 8, 7, 5, 2]
A = bpcuctieu(dulieu)
print(f"Phương trình tuyến tính: y = {A[0]:.1f} + {A[1]:.1f} * x")


Phương trình tuyến tính: y = 10.2 + -1.9 * x
