THI CUỐI KỲ

In [24]:
# Câu 1
import numpy as np
from numpy.linalg import norm
from math import acos, degrees

A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3], [1, 4, -2], [0, 2, 5]])

# a
tong = A + B
tichtuyen = 2*A + 3*B

# b
tichvohuong = A @ B
goc = degrees(acos(tichvohuong / (norm(A)*norm(B))))

# c
CCT = C @ C.T

tong, tichtuyen, tichvohuong, round(goc,3), CCT



(array([2, 3, 1, 6]),
 array([ 3, 11,  2, 14]),
 np.int64(-5),
 99.594,
 array([[14, -8, 13],
        [-8, 21, -2],
        [13, -2, 29]]))

In [41]:
# Câu 2
from numpy.linalg import det, matrix_rank

M = np.array([[2, -1, 3, 0],[1, 4, -2, 5],[0, 2, 6, -3],[-1, 0, 1, 4]])

N = np.array([[1, 3, -2, 0],[4, -1, 5, 2],[0, 2, 3, -1],[-3, 1, 0, 4]])

# a
print("M × N =\n", M @ N)

# b
det_M = det(M)
print("Định thức của M =", det_M)

# c
print("Hạng của N =", matrix_rank(N))




M × N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
Định thức của M = 409.00000000000017
Hạng của N = 4


In [44]:
# Câu 3
from numpy.linalg import inv

P = np.array([[3, -1, 0, 2],[1, 4, -2, 0],[0, 1, 5, -1],[2, 0, 1, 3]])

b_vec = np.array([6, 8, 3, 7])

# a
if det(P) != 0:
    P_inv = inv(P)
    print("P khả nghịch. Ma trận nghịch đảo:\n", P_inv)

# b
    x = P_inv @ b_vec
    print("Nghiệm x =", x)

# c
    check = P @ x
    print("Kiểm tra P · x =", check)
else:
    print("P không khả nghịch.")


P khả nghịch. Ma trận nghịch đảo:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
Nghiệm x = [2.         1.71428571 0.42857143 0.85714286]
Kiểm tra P · x = [6. 8. 3. 7.]


In [ ]:
# Câu 4
import numpy as np

# a
Q = np.array([ [5, -2, 1],[0, 3, -1],[2, 0, 4]])

print("Ma trận Q:")
print(Q)

eigenvalues, eigenvectors = np.linalg.eig(Q)
print("Giá trị riêng:")
print(eigenvalues)

# b 
print("\nVector riêng (mỗi cột là một vector riêng):")
print(eigenvectors)

# c
normalized = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("\nCác vector riêng sau chuẩn hóa:")
print(normalized)



Ma trận Q:
[[ 5 -2  1]
 [ 0  3 -1]
 [ 2  0  4]]
Giá trị riêng:
[6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]

Vector riêng (mỗi cột là một vector riêng):
[[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]

Các vector riêng sau chuẩn hóa:
[[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]


In [45]:
# Câu 5
import numpy as np

# a
R = np.array([[4, -1, 2],[1, 3, -2],[0, 2, 5]])

b = np.array([12, 5, 9])

print("Ma trận R:")
print(R)
print("Vector b:")
print(b)

x = np.linalg.solve(R, b)
print("Nghiệm x của hệ Rx = b:")
print(x)

# b
det_R = np.linalg.det(R)
print("Định thức của R =", round(det_R, 3))

if det_R != 0:
    R_inv = np.linalg.inv(R)
    print("Ma trận nghịch đảo R^-1:")
    print(R_inv)

    x_check = R_inv @ b
    print("Nghiệm tính bằng R^-1 × b:")
    print(x_check)
    print("So sánh với np.linalg.solve:", x)
else:
    print("R không khả nghịch.")

# c
fro_norm = np.linalg.norm(R, 'fro')
print("Chuẩn Frobenius của R =", round(fro_norm, 3))



Ma trận R:
[[ 4 -1  2]
 [ 1  3 -2]
 [ 0  2  5]]
Vector b:
[12  5  9]
Nghiệm x của hệ Rx = b:
[2.78823529 1.52941176 1.18823529]
Định thức của R = 85.0
Ma trận nghịch đảo R^-1:
[[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
Nghiệm tính bằng R^-1 × b:
[2.78823529 1.52941176 1.18823529]
So sánh với np.linalg.solve: [2.78823529 1.52941176 1.18823529]
Chuẩn Frobenius của R = 8.0
