In [13]:
# Câu 5
import numpy as np

# a)

R = np.array([
    [2, 0, 1],
    [1, -2, 3],
    [-1, 1, 4]
])

b = np.array([10, 8, 7])

print("Ma trận R:")
print(R)
print("Vector b:")
print(b)

x = np.linalg.solve(R, b)
print("Nghiệm x của hệ Rx = b:")
print(x)

# b) 

det_R = np.linalg.det(R)
print("Định thức của R =", round(det_R, 3))

if det_R != 0:
    R_inv = np.linalg.inv(R)
    print("Ma trận nghịch đảo R^-1:")
    print(R_inv)

    x_check = R_inv @ b
    print("Nghiệm tính bằng R^-1 × b:")
    print(x_check)
    print("So sánh với np.linalg.solve:", x)
else:
    print("R không khả nghịch.")

# c) 

fro_norm = np.linalg.norm(R, 'fro')
print("Chuẩn Frobenius của R =", round(fro_norm, 3))


Ma trận R:
[[ 2  0  1]
 [ 1 -2  3]
 [-1  1  4]]
Vector b:
[10  8  7]
Nghiệm x của hệ Rx = b:
[3.82608696 1.43478261 2.34782609]
Định thức của R = -23.0
Ma trận nghịch đảo R^-1:
[[ 0.47826087 -0.04347826 -0.08695652]
 [ 0.30434783 -0.39130435  0.2173913 ]
 [ 0.04347826  0.08695652  0.17391304]]
Nghiệm tính bằng R^-1 × b:
[3.82608696 1.43478261 2.34782609]
So sánh với np.linalg.solve: [3.82608696 1.43478261 2.34782609]
Chuẩn Frobenius của R = 6.083


In [ ]:
# Câu 4
import numpy as np

# a) 

Q = np.array([
    [1, 3, -2],
    [4, -1, 0],
    [0, 1, 2]
])

print("Ma trận Q:")
print(Q)

eigenvalues, eigenvectors = np.linalg.eig(Q)
print("Giá trị riêng:", eigenvalues)

# b) 

print("Vector riêng (mỗi cột là một vector riêng):")
print(eigenvectors)

# c) 

normalized = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("Các vector riêng sau chuẩn hóa:")
print(normalized)


Ma trận Q:
[[ 1  3 -2]
 [ 4 -1  0]
 [ 0  1  2]]
Giá trị riêng: [-3.79224946+0.j          2.89612473+0.76033969j  2.89612473-0.76033969j]
Vector riêng (mỗi cột là một vector riêng):
[[ 0.56674477+0.j          0.5918019 +0.11549181j  0.5918019 -0.11549181j]
 [-0.81188272+0.j          0.60758004+0.j          0.60758004-0.j        ]
 [ 0.14016708+0.j          0.39421145-0.33447867j  0.39421145+0.33447867j]]
Các vector riêng sau chuẩn hóa:
[[ 0.56674477+0.j          0.5918019 +0.11549181j  0.5918019 -0.11549181j]
 [-0.81188272+0.j          0.60758004+0.j          0.60758004-0.j        ]
 [ 0.14016708+0.j          0.39421145-0.33447867j  0.39421145+0.33447867j]]


In [11]:
# Câu 3
import numpy as np

# a) 

P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

b = np.array([4, 7, 9, 5])

print("Ma trận P:")
print(P)
print("Vector b:")
print(b)

det_P = np.linalg.det(P)
print("Định thức của P =", round(det_P, 3))

if det_P != 0:
    P_inv = np.linalg.inv(P)
    print("Ma trận nghịch đảo P^-1:")
    print(P_inv)

# b) 

    x = P_inv @ b
    print("Nghiệm x =", x)

# c) 

    b_check = P @ x
    print("P × x =", b_check)
    print("So sánh với b:", b)
else:
    print("P không khả nghịch, không thể giải bằng nghịch đảo.")


Ma trận P:
[[ 2  1  0  1]
 [ 0  3  1 -1]
 [ 1  0  4  2]
 [ 0  1  0  3]]
Vector b:
[4 7 9 5]
Định thức của P = 86.0
Ma trận nghịch đảo P^-1:
[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]
Nghiệm x = [0.46511628 2.10465116 1.65116279 0.96511628]
P × x = [4. 7. 9. 5.]
So sánh với b: [4 7 9 5]


In [10]:
# Câu 2
import numpy as np

M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

print("Ma trận M:")
print(M)
print("Ma trận N:")
print(N)

# a) 
product = M @ N
print("Tích M × N là:")
print(product)

# b) 
det_M = np.linalg.det(M)
print("Định thức của M =", round(det_M, 3))

# c) 
rank_N = np.linalg.matrix_rank(N)
print("Hạng của ma trận N =", rank_N)



Ma trận M:
[[1 2 3 0]
 [4 5 6 1]
 [7 8 9 2]
 [0 1 1 0]]
Ma trận N:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Tích M × N là:
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]
Định thức của M = 0.0
Hạng của ma trận N = 2


In [ ]:
# Câu 1
import numpy as np

# a)

A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])

print("Vector A:", A)
print("Vector B:", B)

sum_AB = A + B
print("Tổng A + B =", sum_AB)

scaled_diff = 3 * A - 2 * B
print("Biểu thức 3A - 2B =", scaled_diff)

# b) 

dot_product = np.dot(A, B)
print("Tích vô hướng A · B =", dot_product)

norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)

cos_theta = dot_product / (norm_A * norm_B)
theta_deg = np.degrees(np.arccos(cos_theta))
print("Góc giữa A và B ≈", round(theta_deg, 3), "độ")

# c) 
C = np.array([
    [0, 3, 4],
    [1, 2, -1],
    [2, -1, 0]
])

print("Ma trận C:")
print(C)

C_T = C.T
print("Chuyển vị C^T:")
print(C_T)

CTC = C_T @ C
print("Tích C^T × C:")
print(CTC)




Vector A: [ 2 -1  3  0]
Vector B: [ 1  4 -2  5]
Tổng A + B = [3 3 1 5]
Biểu thức 3A - 2B = [  4 -11  13 -10]
Tích vô hướng A · B = -8
Góc giữa A và B ≈ 108.376 độ
Ma trận C:
[[ 0  3  4]
 [ 1  2 -1]
 [ 2 -1  0]]
Chuyển vị C^T:
[[ 0  1  2]
 [ 3  2 -1]
 [ 4 -1  0]]
Tích C^T × C:
[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]
